image: prakticeai/generic-bitbucket-pipeline-image
pipelines:
  branches:
    release:
      - step:
          name: deploy to server
          deployment: test
          script:
            - eb init -r "ap-south-1" " tedx-aiactr" <<< $'n'
            - eb deploy
